### ISSUE TITLE
Can not found block resource

### ISSUE THREAD

**Issue by v-nhandt21** [ofdl-robotics-tw/WRO-RoboSports-Example#1]
I download the source code and open it with ev3 labview, but it ca not compile

![20230617_190720](https://github.com/ofdl-robotics-tw/WRO-RoboSports-Example/assets/36092323/c03d1fa4-3b05-49ee-a5d6-69f9ad9f1500)

**Comment by a10036gt** [comment]
Please make sure all block that program use has been import.
Pixy2 Lite Block
Advanced Motor Controller block
